In [1]:
import numpy as np

In [2]:
arr=np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [4]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
for x in arr1:
    print(x)

[1 2 3]
[4 5 6]
[7 8 9]


In [6]:
for x in arr1:
    for i in x:
        print(i)

1
2
3
4
5
6
7
8
9


In [7]:
arr2=np.array([[[1,2,3,],[20,30,40]],[[25,65,32],[100,105,107]]])
print(arr2)

[[[  1   2   3]
  [ 20  30  40]]

 [[ 25  65  32]
  [100 105 107]]]


In [8]:
for x in arr2:
    print(x)

[[ 1  2  3]
 [20 30 40]]
[[ 25  65  32]
 [100 105 107]]


In [9]:
for x in arr2:  #loop run 3 time because of 3d array
    for y in x:
        for z in y:
            print(z)

1
2
3
20
30
40
25
65
32
100
105
107


In [10]:
for x in np.nditer(arr2):  #because of np.nditer we dont have to run loop 3 times
    print(x)

1
2
3
20
30
40
25
65
32
100
105
107


In [11]:
arr3=np.array([[1,2,3,4],[10,12,13,14]])
print(arr3)

[[ 1  2  3  4]
 [10 12 13 14]]


In [12]:
for x in np.nditer(arr3[:,::3]):
    print(x)

1
4
10
14


In [13]:
arr4=np.array([[1,2,3,4],[10,12,13,14],[20,35,65,45],[85,35,75,61]])
print(arr4)

[[ 1  2  3  4]
 [10 12 13 14]
 [20 35 65 45]
 [85 35 75 61]]


In [14]:
for x in np.nditer(arr4[0:4,0:3:2]):
    print(x)

1
3
10
13
20
65
85
75


In [15]:
for idx, x in np.ndenumerate(arr4):  #idx means index number that is position
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 10
(1, 1) 12
(1, 2) 13
(1, 3) 14
(2, 0) 20
(2, 1) 35
(2, 2) 65
(2, 3) 45
(3, 0) 85
(3, 1) 35
(3, 2) 75
(3, 3) 61


In [16]:
arr1=np.array([10,12,15,14])
arr2=np.array([45,35,25,12])
arr3=np.concatenate((arr1,arr2))
print(arr3)

[10 12 15 14 45 35 25 12]


In [17]:
arr1=np.array([[10,12],[15,14]])
arr2=np.array([[45,35],[25,12]])
print(arr1)
print(arr2)

[[10 12]
 [15 14]]
[[45 35]
 [25 12]]


In [18]:
arr3=np.concatenate((arr1,arr2),axis=1)
print(arr3)

[[10 12 45 35]
 [15 14 25 12]]


In [19]:
arr4=np.array([[10,12],[15,14],[45,65]])
arr5=np.array([[45,35],[25,12],[85,25]])
arr6=np.array([[95,65],[45,15],[75,85]])
arr7=np.concatenate((arr4,arr5,arr6),axis=1)
print(arr7)

[[10 12 45 35 95 65]
 [15 14 25 12 45 15]
 [45 65 85 25 75 85]]


In [20]:
arr1=np.array([10,12,15,14])
arr2=np.array([45,35,25,12])
arr3=np.stack((arr1,arr2),axis=1)  #Rows data converted in coulmn
print(arr3)

[[10 45]
 [12 35]
 [15 25]
 [14 12]]


In [21]:
arr4=np.array([[10,12],[15,14],[45,65]])
arr5=np.array([[45,35],[25,12],[85,25]])
arr6=np.array([[95,65],[45,15],[75,85]])
arr3=np.stack((arr4,arr5,arr6),axis=1)
print(arr3)

[[[10 12]
  [45 35]
  [95 65]]

 [[15 14]
  [25 12]
  [45 15]]

 [[45 65]
  [85 25]
  [75 85]]]


In [22]:
arr4=np.array([[10,12],[15,14],[45,65]])
arr5=np.array([[45,35],[25,12],[85,25]])
arr6=np.array([[95,65],[45,15],[75,85]])
arr3=np.hstack((arr4,arr5,arr6))  #hstack works as concatnate with axis=1
print(arr3)

[[10 12 45 35 95 65]
 [15 14 25 12 45 15]
 [45 65 85 25 75 85]]


In [23]:
arr4=np.array([[10,12],[15,14],[45,65]])
arr5=np.array([[45,35],[25,12],[85,25]])
arr6=np.array([[95,65],[45,15],[75,85]])
arr3=np.vstack((arr4,arr5,arr6))  
print(arr3)

[[10 12]
 [15 14]
 [45 65]
 [45 35]
 [25 12]
 [85 25]
 [95 65]
 [45 15]
 [75 85]]


In [24]:
arr4=np.arange(1,21)
print(arr4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [25]:
newarr4=np.array_split(arr4, 5)
print(newarr4)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12]), array([13, 14, 15, 16]), array([17, 18, 19, 20])]


In [26]:
newarr4=np.array_split(arr4, 5)
print(newarr4[0])
print(newarr4[1])
print(newarr4[3])
print(newarr4[2])

[1 2 3 4]
[5 6 7 8]
[13 14 15 16]
[ 9 10 11 12]


In [27]:
arr4=np.array([[10,12,45],[25,15,14],[75,45,65]])
arr4=np.array_split(arr1, 2)
print(arr4)
print(arr4[0])
print(arr4[1])

[array([10, 12]), array([15, 14])]
[10 12]
[15 14]


In [28]:
arr1=np.array([[1,2],[2,3],[4,5],[8,9],[9,6]])
arr4=np.array_split(arr1, 2)
print(arr4[0])
print(arr4[0][2][1])

[[1 2]
 [2 3]
 [4 5]]
5
