In [2]:
import numpy as np

In [5]:
# Create an 8x3 integer array from a range between 10 to 34 with a difference of 1
array = np.arange(10, 34).reshape(8, 3)
array

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [8]:
# Split the array into four equal-sized sub-arrays
sub_arrays = np.array_split(array, 4)
sub_arrays

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

In [10]:
# Print the sub-arrays
for i, sub_array in enumerate(sub_arrays):
    print(f"Sub-array {i + 1}:\n{sub_array}\n")

Sub-array 1:
[[10 11 12]
 [13 14 15]]

Sub-array 2:
[[16 17 18]
 [19 20 21]]

Sub-array 3:
[[22 23 24]
 [25 26 27]]

Sub-array 4:
[[28 29 30]
 [31 32 33]]

